#########################################################################
#  _____  _                    _     _____              _               #
# /  __ \| |                  | |   | ___ \            | |              #
# | /  \/| |__   _   _  _ __  | | __| |_/ / _   _  ___ | |_  ___  _ __  #
# | |    |  _ \ | | | || '_ \ | |/ /| ___ \| | | |/ __|| __|/ _ \| '__| #
# | \__/\| | | || |_| || | | ||   < | |_/ /| |_| |\__ \| |_|  __/| |    #
#  \____/|_| |_| \__,_||_| |_||_|\_\\____/  \__,_||___/ \__|\___||_|    #
#                                                                       #
#                           v1.1.3 by Biscut                            #
#########################################################################

chunkbuster:
  material: 'ENDER_PORTAL_FRAME'
  name: '&aChunk Buster'
  lore:
    - '&7Radius: &e{area}'
    - ''
    - '&7Right click to place and destroy'
    - '&7all the blocks in your chunk radius.'

# This amount of blocks will be processed from the queue per second
# High numbers will make the blocks disappear instantly, but especially with
# chunkbusters with 5+ radius, it may lag the server.
blocks-removed-per-tick: 600

# Change this to false if you don't want to be able to destroy wilderness chunks.
can-place-in-wilderness: true

# Whole number - Wait this amount of seconds before executing the chunkbuster.
# This is useful if your players don't have fly etc. 0 means no delay.
chunkbuster-warmup: 0

# If true, the "clearing-in-seconds" message will send every second, and then finally the "clearing-chunks" message.
# If false, it will only say the first clearing message and then the "clearing-chunks" message.
warmup-message-every-second: true

# Whether to drop the items on the floor if inventory is full.
full-inv-drop-on-floor: false

# The minimum factions role for using chunkbusters
# For FactionsUUID/SavageFactions, set this to either 'leader'/'admin', 'coleader', 'moderator', 'member'/'normal', 'recruit'/'any'
# For MassiveCore Factions, set this to either 'leader'/'admin', 'officer', 'member'/'normal', 'recruit'/'any'
# 'any' means everyone can use chunkbusters, regardless of faction role.
minimum-factions-role: 'any'

confirm-gui:
  # Maximum 6
  rows: 3
  # Please use 1.8 material names from here or any other 1.8 javadocs.
  # https://biscut.xyz/javadocs/org/bukkit/Material.html
  # Damage values supported.
  confirm-material: 'WOOL:5'
  cancel-material: 'WOOL:14'
  # Please do not leave leave any of these below texts empty ('') please
  title: '&7CONFIRM CHUNK BUSTER'
  confirm-block-name: '&aCONFIRM'
  cancel-block-name: '&cDENY'
  # The lores of the confirm and cancel blocks. For no lore, put []. Otherwise
  # make it a list (-) like the chunkbuster lore.
  confirm-block-lore: []
  cancel-block-lore:
    - ''

messages:
  give: '&aYou gave {player} {amount} chunkbuster(s).'
  receive: '&aYou have received {amount} chunkbuster(s).'
  no-permission-command: '&cNo permission!'
  no-permission-place: '&cYou cannot place chunkbusters!'
  no-faction: '&cYou must have a faction to use a chunk buster!'
  # These 2 messages will display depending on what you chose for "can-place-in-wilderness".
  only-wilderness-and-claim: '&cYou can only place chunk busters in your territory or in wilderness!'
  only-claim: '&cYou can only place chunk busters in your territory!'
  region-protected: '&cYou cannot place chunk busters in this region!'
  clearing-chunks: '&aClearing the chunk(s)!'
  #This will only show if "chunkbuster-activation-delay" is above 0
  clearing-in-seconds: '&aChunk(s) will clear in {seconds} second(s).'
  not-minimum-role: '&cYou must be a faction (insert role) to use chunkbusters.'

# Please do not edit :)
config-version: 1.3
