main: xyz.biscut.chunkbuster.ChunkBuster
version: 1.1.1
name: ChunkBuster
author: Biscut
softdepend: [MassiveCore, Factions, WorldGuard]
commands:
  chunkbuster:
    description: Give a player (a) chunkbuster(s).
    aliases: [cb]
permissions:
  chunkbuster.admin:
    description: Access to the /cb command.
    default: op